name: Electron Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        
      - name: Test Dice
        run: npm test
        
      - name: Build Electron App
        run: npm run dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-dist
          path: dist
